#!/usr/bin/env node
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  checkContractPreflight,
  compareProtectedProjectState,
  parseFrontmatter,
  snapshotProtectedProjectState,
  validateCompletion,
} from "./_router-core.mjs";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const skillRoot = resolve(scriptDir, "..");
const sourceRoot = resolve(skillRoot, "..", "..");
const fixture = mkdtempSync(resolve(tmpdir(), "app-factory-router-test-"));
const architecture = resolve(fixture, "docs", "architecture");
mkdirSync(architecture, { recursive: true });

try {
  const bundledConfig = JSON.parse(readFileSync(resolve(skillRoot, "assets", "opencode.backend.json"), "utf8"));
  assert.equal(bundledConfig.model, "opencode-go/kimi-k2.7-code");
  assert.equal(bundledConfig.permission.edit["**/docs/architecture/**"], "deny");
  assert.equal(bundledConfig.permission.edit["**/.agents/**"], "deny");
  assert.equal(bundledConfig.permission.bash["*"], "deny");
  assert.equal(bundledConfig.permission.bash["git status --short"], "allow");
  assert.equal(bundledConfig.permission.bash["python manage.py makemigrations*"], undefined);
  if (existsSync(resolve(sourceRoot, "opencode.json"))) {
    const sourceConfig = JSON.parse(readFileSync(resolve(sourceRoot, "opencode.json"), "utf8"));
    assert.deepEqual(bundledConfig, sourceConfig, "root and bundled OpenCode configs must stay synchronized");
  }

  const missing = checkContractPreflight(fixture);
  assert.equal(missing.ok, false);

  for (const name of ["backend-plan.md", "domain-model.md", "api-contract.md", "security-contract.md", "backend-validation-plan.md"]) {
    writeFileSync(resolve(architecture, name), `# ${name}\n`, "utf8");
  }
  writeFileSync(
    resolve(architecture, "backend-validation-plan.md"),
    "# Backend validation plan\n\n```bash\npython manage.py test\n```\n",
    "utf8",
  );
  writeFileSync(resolve(architecture, "backend-implementation-contract.md"), [
    "---",
    "status: approved",
    "contract_version: 2",
    "approved_at: 2026-07-13",
    "---",
    "# Implementation",
    "",
  ].join("\n"), "utf8");
  const manifest = {
    contract_version: 2,
    status: "approved",
    services: [{ id: "django", runtime: "django", local_port: 8000, root_urlconf: "config.urls" }],
    environment_bindings: [],
    invariants: [{
      id: "BR-001",
      statement: "An approved router fixture invariant is enforced.",
      enforcement: ["apps.orders.services.create_order"],
      required_tests: ["test_router_fixture_invariant"],
    }],
    endpoints: [{
      id: "API-001",
      method: "POST",
      path: "/api/orders/",
      controller: "apps.orders.api.controllers.create_order.CreateOrderController",
      request_dto: "apps.orders.dtos.create_order.CreateOrderRequestDTO",
      response_dto: null,
      mapper: "apps.orders.mappers.create_order.to_service_input",
      service: "apps.orders.services.create_order.CreateOrderService",
      repositories: ["apps.orders.repositories.contracts.OrderRepository"],
      required_tests: ["test_create_order_endpoint_contract"],
    }],
    allowed_execution_commands: ["python manage.py makemigrations orders"],
    required_validations: [{ id: "VAL-001", kind: "test", command: "python manage.py test", required: true }],
  };
  const manifestPath = resolve(architecture, "backend-contract-manifest.json");
  writeFileSync(manifestPath, JSON.stringify(manifest, null, 2), "utf8");

  assert.deepEqual(parseFrontmatter("---\nstatus: approved\ncontract_version: 2\n---\n"), {
    status: "approved",
    contract_version: "2",
  });
  const approved = checkContractPreflight(fixture);
  assert.equal(approved.ok, true);
  assert.equal(approved.contractVersion, 2);
  assert.deepEqual(approved.contractRequiredTests, {
    "BR-001": ["test_router_fixture_invariant"],
    "API-001": ["test_create_order_endpoint_contract"],
  });

  const migrationDirectory = resolve(fixture, "backend", "apps", "orders", "migrations");
  mkdirSync(migrationDirectory, { recursive: true });
  const existingMigration = resolve(migrationDirectory, "0001_initial.py");
  writeFileSync(existingMigration, "# Generated by Django\n", "utf8");
  const protectedBefore = snapshotProtectedProjectState(fixture);
  writeFileSync(resolve(migrationDirectory, "0002_order_status.py"), "# Generated by Django\n", "utf8");
  assert.deepEqual(compareProtectedProjectState(protectedBefore, snapshotProtectedProjectState(fixture)), []);

  const backendPlanPath = resolve(architecture, "backend-plan.md");
  const backendPlan = readFileSync(backendPlanPath, "utf8");
  writeFileSync(backendPlanPath, `${backendPlan}\nchanged during execution\n`, "utf8");
  assert.ok(compareProtectedProjectState(
    protectedBefore,
    snapshotProtectedProjectState(fixture),
  ).some((error) => error.includes("protected file was modified")));
  writeFileSync(backendPlanPath, backendPlan, "utf8");

  writeFileSync(existingMigration, "# Generated by Django\n# patched\n", "utf8");
  assert.ok(compareProtectedProjectState(
    protectedBefore,
    snapshotProtectedProjectState(fixture),
  ).some((error) => error.includes("existing migration was modified")));
  writeFileSync(existingMigration, "# Generated by Django\n", "utf8");

  const malformedManifest = structuredClone(manifest);
  delete malformedManifest.endpoints[0].mapper;
  delete malformedManifest.required_validations[0].kind;
  delete malformedManifest.services[0].root_urlconf;
  malformedManifest.services[0].unsupported = true;
  malformedManifest.allowed_execution_commands = ["python manage.py makemigrations orders; Set-Content contract hacked"];
  writeFileSync(manifestPath, JSON.stringify(malformedManifest, null, 2), "utf8");
  const malformed = checkContractPreflight(fixture);
  assert.equal(malformed.ok, false);
  assert.ok(malformed.errors.some((error) => error.includes("missing required property mapper")));
  assert.ok(malformed.errors.some((error) => error.includes("missing required property kind")));
  assert.ok(malformed.errors.some((error) => error.includes("missing required property root_urlconf")));
  assert.ok(malformed.errors.some((error) => error.includes("unsupported property unsupported")));
  assert.ok(malformed.errors.some((error) => error.includes("non-compound Django makemigrations")));
  writeFileSync(manifestPath, JSON.stringify(manifest, null, 2), "utf8");

  const completion = {
    task_id: "router-test",
    contract_version: 2,
    status: "completed",
    changed_files: [],
    commands: [
      { command: "python manage.py test", result: "passed", exit_code: 0, notes: [] },
    ],
    generated_migrations: [],
    tests: [],
    architecture_scan: {},
    contract_evidence: {
      "BR-001": {
        implementation: ["backend/apps/orders/services/create_order.py"],
        tests: ["test_router_fixture_invariant"],
        result: "passed",
        notes: [],
      },
      "API-001": {
        implementation: ["backend/apps/orders/api/controllers/create_order.py"],
        tests: ["test_create_order_endpoint_contract"],
        result: "passed",
        notes: [],
      },
    },
    validation_evidence: {
      "VAL-001": { command: "python manage.py test", result: "passed", exit_code: 0, notes: [] },
    },
    contract_deviations: [],
    unresolved_items: [],
    validation_limitations: [],
  };
  assert.deepEqual(validateCompletion(
    completion,
    2,
    ["BR-001", "API-001"],
    { "VAL-001": "python manage.py test" },
    {
      "BR-001": ["test_router_fixture_invariant"],
      "API-001": ["test_create_order_endpoint_contract"],
    },
    "router-test",
    { "VAL-001": "python manage.py test" },
    ["python manage.py makemigrations orders"],
  ), []);

  const unrelatedEvidence = structuredClone(completion);
  unrelatedEvidence.contract_evidence["BR-001"].tests = ["test_unrelated_green_test"];
  assert.ok(validateCompletion(
    unrelatedEvidence,
    2,
    ["BR-001", "API-001"],
    { "VAL-001": "python manage.py test" },
    {
      "BR-001": ["test_router_fixture_invariant"],
      "API-001": ["test_create_order_endpoint_contract"],
    },
    "router-test",
    { "VAL-001": "python manage.py test" },
    ["python manage.py makemigrations orders"],
  ).some((error) => error.includes("missing required test test_router_fixture_invariant")));

  const unapprovedCommand = structuredClone(completion);
  unapprovedCommand.commands.push({
    command: "powershell Set-Content docs/architecture/backend-plan.md hacked",
    result: "passed",
    exit_code: 0,
    notes: [],
  });
  assert.ok(validateCompletion(
    unapprovedCommand,
    2,
    ["BR-001", "API-001"],
    { "VAL-001": "python manage.py test" },
    {
      "BR-001": ["test_router_fixture_invariant"],
      "API-001": ["test_create_order_endpoint_contract"],
    },
    "router-test",
    { "VAL-001": "python manage.py test" },
    ["python manage.py makemigrations orders"],
  ).some((error) => error.includes("unapproved command")));

  const staleTask = structuredClone(completion);
  staleTask.task_id = "older-task";
  assert.ok(validateCompletion(
    staleTask,
    2,
    ["BR-001", "API-001"],
    { "VAL-001": "python manage.py test" },
    {
      "BR-001": ["test_router_fixture_invariant"],
      "API-001": ["test_create_order_endpoint_contract"],
    },
    "router-test",
    { "VAL-001": "python manage.py test" },
    ["python manage.py makemigrations orders"],
  ).some((error) => error.includes("active run")));

  const blocked = {
    ...structuredClone(completion),
    status: "blocked",
    contract_evidence: {},
    validation_evidence: {},
    unresolved_items: ["Database is unavailable"],
  };
  assert.deepEqual(validateCompletion(
    blocked,
    2,
    ["BR-001", "API-001"],
    { "VAL-001": "python manage.py test" },
    {
      "BR-001": ["test_router_fixture_invariant"],
      "API-001": ["test_create_order_endpoint_contract"],
    },
    "router-test",
    { "VAL-001": "python manage.py test" },
    ["python manage.py makemigrations orders"],
  ), []);

  const route = spawnSync(process.execPath, [
    resolve(scriptDir, "route-backend-execution.mjs"),
    "--project-root", fixture,
    "--task-id", "router-self-test",
    "--dry-run",
  ], { encoding: "utf8", windowsHide: true });
  assert.equal(route.status, 0, route.stderr);
  const result = JSON.parse(route.stdout.trim());
  assert.ok(["codex-fallback-required", "opencode-ready"].includes(result.route));
  assert.equal(result.project_root, fixture);
  if (result.artifacts?.run_dir) rmSync(result.artifacts.run_dir, { recursive: true, force: true });

  process.stdout.write("router tests passed\n");
} finally {
  rmSync(fixture, { recursive: true, force: true });
}
